### ISSUE TITLE
similar to shell update problem #6 that was closed. vim exception Ctrl-s or F5

### ISSUE THREAD

**Issue by ghost** [ivanov/vim-ipython#106]
(disclaimer - first issue, so I hope this follows common etiquette)
Linux 3.10.17-smp #2 SMP i686 Intel Pentium Dual
vim 7.4 compiled on slackware 14 
ipython 2.2.0 
.bashrc and .vimrc modified as directed in tutorial

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "///.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 478, in f_with_update f(*args)
  File "///.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 487, in run_this_file
  msg_id = send('%%run %s %s' % (run_flags, repr(vim.current.buffer.name),))
NameError: global name 'send' is not defined

also 
:py print km
None
:py send = km.shell_channel.execute

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'shell_channel'

This was working fine, and it seemed to stop working after installing virtualenv 
and virtualenvwraper (required editing .bashrc) but reversing the changes does
not fix the problem.

ipython notebook qtconsole and ipython kernels all work.
Thank you.

**Comment by noreun** [comment]
Similar, but different... Any luck solving this? Same problem here.

_Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 502, in f_with_update f(*args)
  File "~/.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 511, in run_this_file
msg_id = send('%%run %s %s' % (run_flags, repr(vim.current.buffer.name),))
NameError: global name 'send' is not defined_

**Comment by noreun** [comment]
For me downgrading ipython to 3.2.3 did the trick... perhaps related to #155 ?
