### ISSUE TITLE
Traceback and NameError on anaconda python 2.7

### ISSUE THREAD

**Issue by hayd** [ivanov/vim-ipython#113]
I'm new to vim, please forgive me if I have done something silly (hopefully that's the case!).

I get this error when I run `:IPython`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/andy/.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 151, in km_from_string
    km.load_connection_file()
  File "/Users/andy/anaconda/lib/python2.7/site-packages/IPython/kernel/connect.py", line 495, in load_connection_file
    cfg = json.loads(f.read())
  File "/Users/andy/anaconda/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/andy/anaconda/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/andy/anaconda/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

and ctrl+s:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/andy/.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 478, in f_with_update
    f(*args)
  File "/Users/andy/.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 513, in run_this_line
    msg_id = send(line)
NameError: global name 'send' is not defined
```

_Note: I have an ipython (2.1.0) console open._

**Comment by paolodina** [comment]
I'm stuck at the same point, any workaround?

**Comment by Thomas-van-Dijk** [comment]
Same for me..

**Comment by spencerns** [comment]
same for me.

**Comment by sfuller1979** [comment]
same for me

**Comment by ivanov** [comment]
Do you have an ipython kernel running? vim-ipython does not currently start a new kernel, it can only connect to kernels that have already been started via either `ipython kernel` or `ipython console` or by opening up a notebook file in `jupyter`
