### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by fakufaku** [ivanov/vim-ipython#131]
Hi,

I have installed the latest version in ftplugin/python and when I launch a python file `vim test.py`, and type `:IPython`, I have the following errror.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/scheibler/.vim/ftplugin/python/vim_ipython.py", line 151, in km_from_string
    km.load_connection_file()
  File "/Users/scheibler/anaconda/lib/python2.7/site-packages/IPython/kernel/connect.py", line 504, in load_connection_file
    cfg = json.load(f)
  File "/Users/scheibler/anaconda/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/Users/scheibler/anaconda/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/scheibler/anaconda/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/scheibler/anaconda/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by fakufaku** [comment]
Ok, sorry for the noob issue. I had not launched an ipython session...
