### ISSUE TITLE
Not working after installing with Vundle

### ISSUE THREAD

**Issue by aftnix** [ivanov/vim-ipython#141]
Installed with vundle by 

```
Plugin 'ivanov/vim-ipython'

```

Then doing a `!PluginInstall`

Which seems to go Ok...

```
$ tree ~/.vim/bundle/vim-ipython/
/home/aftnix/.vim/bundle/vim-ipython/
├── CONTRIBUTING.md
├── ftplugin
│   └── python
│       ├── ipy.vim
│       └── vim_ipython.py
├── README.rst
├── test
│   └── simple.vader
└── TODO.md

```

But after it, I don't seem to find `:help IPython` or `:IPython` commands available.

**Comment by neerav1985** [comment]
That's  correct. Temporary solution is to source it with the full path. I tried doing that,but, after that, `:IPython` gives below error.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 39, in km_from_string
ImportError: No module named zmq.blockingkernelmanager
```

**Comment by aftnix** [comment]
Currently using it with by directly sourcing `ipy.vim`. But it all seems like a path related issue and there must be a very simple fix.

**Comment by albasili** [comment]
I am sourcing ipy.vim but nothing happens and the command ``IPython`` is still unavailable. Any ideas?
