### ISSUE TITLE
Connecting multiple times broken

### ISSUE THREAD

**Issue by naupaka** [ivanov/vim-ipython#97]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 116, in km_from_string
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipython-1.
1.0-py2.7.egg/IPython/kernel/connect.py", line 202, in find_connection_file
    app = IPApp.instance()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipython-1.
1.0-py2.7.egg/IPython/config/configurable.py", line 360, in instance
    '%s are being created.' % cls.__name__
IPython.config.configurable.MultipleInstanceError: Multiple incompatible subclass instances of BaseIPythonApplication
are being created.
```

**Comment by naupaka** [comment]
Closing as out of date
